// <auto-generated />
using System;
using HackSystem.WebAPI.DataAccess;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace HackSystem.WebAPI.DataAccess.Migrations;

    [DbContext(typeof(HackSystemDBContext))]
    [Migration("20210730151513_DBMigration_1")]
    partial class DBMigration_1
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.0-preview.6.21352.1");

            modelBuilder.Entity("HackSystem.WebAPI.Model.Identity.HackSystemRole", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("TEXT");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("TEXT");

                    b.Property<int>("Level")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .HasMaxLength(256)
                        .HasColumnType("TEXT");

                    b.Property<string>("NormalizedName")
                        .HasMaxLength(256)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedName")
                        .IsUnique()
                        .HasDatabaseName("RoleNameIndex");

                    b.ToTable("AspNetRoles", (string)null);

                    b.HasData(
                        new
                        {
                            Id = "msaspnet-core-role-hack-system000001",
                            ConcurrencyStamp = "8ef3768d-cdd3-43a4-9338-c549cec56942",
                            Level = 0,
                            Name = "Hacker",
                            NormalizedName = "HACKER"
                        },
                        new
                        {
                            Id = "msaspnet-core-role-hack-system000002",
                            ConcurrencyStamp = "43daf209-df6b-499c-83e5-94ea05cf8997",
                            Level = 0,
                            Name = "Commander",
                            NormalizedName = "COMMANDER"
                        });
                });

            modelBuilder.Entity("HackSystem.WebAPI.Model.Identity.HackSystemUser", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("TEXT");

                    b.Property<int>("AccessFailedCount")
                        .HasColumnType("INTEGER");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("TEXT");

                    b.Property<string>("Email")
                        .HasMaxLength(256)
                        .HasColumnType("TEXT");

                    b.Property<bool>("EmailConfirmed")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Level")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("LockoutEnabled")
                        .HasColumnType("INTEGER");

                    b.Property<DateTimeOffset?>("LockoutEnd")
                        .HasColumnType("TEXT");

                    b.Property<string>("NormalizedEmail")
                        .HasMaxLength(256)
                        .HasColumnType("TEXT");

                    b.Property<string>("NormalizedUserName")
                        .HasMaxLength(256)
                        .HasColumnType("TEXT");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("TEXT");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("TEXT");

                    b.Property<bool>("PhoneNumberConfirmed")
                        .HasColumnType("INTEGER");

                    b.Property<string>("SecurityStamp")
                        .HasColumnType("TEXT");

                    b.Property<bool>("TwoFactorEnabled")
                        .HasColumnType("INTEGER");

                    b.Property<string>("UserName")
                        .HasMaxLength(256)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedEmail")
                        .HasDatabaseName("EmailIndex");

                    b.HasIndex("NormalizedUserName")
                        .IsUnique()
                        .HasDatabaseName("UserNameIndex");

                    b.ToTable("AspNetUsers", (string)null);

                    b.HasData(
                        new
                        {
                            Id = "msaspnet-core-user-hack-system000001",
                            AccessFailedCount = 0,
                            ConcurrencyStamp = "baeb86b5-116c-43ae-ade7-489dabd07012",
                            Email = "leon@hack.com",
                            EmailConfirmed = true,
                            Level = 0,
                            LockoutEnabled = true,
                            NormalizedEmail = "LEON@HACK.COM",
                            NormalizedUserName = "LEON",
                            PasswordHash = "AQAAAAEAACcQAAAAEBpsyxgzjSNJvSIm6y3I1jqvKN4iV/IkvwmMrrYR5X8a6pEXza2RwA9xxSXidOiGkQ==",
                            PhoneNumberConfirmed = false,
                            SecurityStamp = "SU6NODNYTSGYJ5NXXYIA7I2M542MLV2V",
                            TwoFactorEnabled = false,
                            UserName = "Leon"
                        },
                        new
                        {
                            Id = "msaspnet-core-user-hack-system000002",
                            AccessFailedCount = 0,
                            ConcurrencyStamp = "a3e94fcc-39cf-4a2f-8b23-f08424042cb8",
                            Email = "commander@hack.com",
                            EmailConfirmed = true,
                            Level = 0,
                            LockoutEnabled = true,
                            NormalizedEmail = "COMMANDER@HACK.COM",
                            NormalizedUserName = "CMD",
                            PasswordHash = "AQAAAAEAACcQAAAAEBLD9HIQLb2pLRH1Vrv1PnOuab+diYEwtCoWFyIx/S+C2nynO4S9NMBUjdQUcVWFrg==",
                            PhoneNumberConfirmed = false,
                            SecurityStamp = "GMGJIR7MWWVSLB2IYMAP445FXWPKZQE5",
                            TwoFactorEnabled = false,
                            UserName = "CMD"
                        },
                        new
                        {
                            Id = "msaspnet-core-user-hack-system000003",
                            AccessFailedCount = 0,
                            ConcurrencyStamp = "93cdc1b8-0c84-4f52-9245-d6ae4bbe5f59",
                            Email = "mathilda@hack.com",
                            EmailConfirmed = true,
                            Level = 0,
                            LockoutEnabled = true,
                            NormalizedEmail = "MATHILDA@HACK.COM",
                            NormalizedUserName = "MATHILDA",
                            PasswordHash = "AQAAAAEAACcQAAAAEDjIsjVamUxv4OQ06Ur/7YnsqddYfO2eQP7UK/Adjs38RIkmBpgTldrfCXZ5QHP1vQ==",
                            PhoneNumberConfirmed = false,
                            SecurityStamp = "2NGFUDFGMLPCBN5U67CHXJEYIDBWQPO3",
                            TwoFactorEnabled = false,
                            UserName = "Mathilda"
                        });
                });

            modelBuilder.Entity("HackSystem.WebAPI.Model.Map.UserMap.UserBasicProgramMap", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("TEXT");

                    b.Property<string>("ProgramId")
                        .HasColumnType("TEXT");

                    b.Property<bool>("Hide")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("PinToDock")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("PinToTop")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Rename")
                        .HasColumnType("TEXT");

                    b.HasKey("UserId", "ProgramId");

                    b.HasIndex("ProgramId");

                    b.HasIndex("UserId");

                    b.HasIndex("UserId", "ProgramId")
                        .IsUnique();

                    b.ToTable("UserBasicProgramMaps");

                    b.HasData(
                        new
                        {
                            UserId = "msaspnet-core-user-hack-system000001",
                            ProgramId = "program0-icon-0828-hack-system000001",
                            Hide = false,
                            PinToDock = true,
                            PinToTop = false
                        },
                        new
                        {
                            UserId = "msaspnet-core-user-hack-system000001",
                            ProgramId = "program0-icon-0828-hack-system000002",
                            Hide = false,
                            PinToDock = true,
                            PinToTop = false
                        },
                        new
                        {
                            UserId = "msaspnet-core-user-hack-system000001",
                            ProgramId = "program0-icon-0828-hack-system000003",
                            Hide = false,
                            PinToDock = true,
                            PinToTop = false
                        },
                        new
                        {
                            UserId = "msaspnet-core-user-hack-system000001",
                            ProgramId = "program0-icon-0828-hack-system000004",
                            Hide = false,
                            PinToDock = true,
                            PinToTop = false
                        },
                        new
                        {
                            UserId = "msaspnet-core-user-hack-system000001",
                            ProgramId = "program0-icon-0828-hack-system000005",
                            Hide = false,
                            PinToDock = true,
                            PinToTop = false
                        },
                        new
                        {
                            UserId = "msaspnet-core-user-hack-system000001",
                            ProgramId = "program0-icon-0828-hack-system000006",
                            Hide = false,
                            PinToDock = true,
                            PinToTop = false
                        },
                        new
                        {
                            UserId = "msaspnet-core-user-hack-system000001",
                            ProgramId = "program0-icon-0828-hack-system000007",
                            Hide = false,
                            PinToDock = false,
                            PinToTop = false
                        },
                        new
                        {
                            UserId = "msaspnet-core-user-hack-system000001",
                            ProgramId = "program0-icon-0828-hack-system000008",
                            Hide = false,
                            PinToDock = true,
                            PinToTop = false
                        },
                        new
                        {
                            UserId = "msaspnet-core-user-hack-system000001",
                            ProgramId = "program0-icon-0828-hack-system000009",
                            Hide = false,
                            PinToDock = true,
                            PinToTop = false
                        },
                        new
                        {
                            UserId = "msaspnet-core-user-hack-system000002",
                            ProgramId = "program0-icon-0828-hack-system000001",
                            Hide = false,
                            PinToDock = true,
                            PinToTop = false
                        },
                        new
                        {
                            UserId = "msaspnet-core-user-hack-system000002",
                            ProgramId = "program0-icon-0828-hack-system000002",
                            Hide = false,
                            PinToDock = true,
                            PinToTop = false
                        },
                        new
                        {
                            UserId = "msaspnet-core-user-hack-system000002",
                            ProgramId = "program0-icon-0828-hack-system000003",
                            Hide = false,
                            PinToDock = true,
                            PinToTop = false
                        },
                        new
                        {
                            UserId = "msaspnet-core-user-hack-system000002",
                            ProgramId = "program0-icon-0828-hack-system000004",
                            Hide = false,
                            PinToDock = true,
                            PinToTop = false
                        },
                        new
                        {
                            UserId = "msaspnet-core-user-hack-system000002",
                            ProgramId = "program0-icon-0828-hack-system000005",
                            Hide = false,
                            PinToDock = true,
                            PinToTop = false
                        },
                        new
                        {
                            UserId = "msaspnet-core-user-hack-system000002",
                            ProgramId = "program0-icon-0828-hack-system000006",
                            Hide = false,
                            PinToDock = true,
                            PinToTop = false
                        },
                        new
                        {
                            UserId = "msaspnet-core-user-hack-system000002",
                            ProgramId = "program0-icon-0828-hack-system000007",
                            Hide = false,
                            PinToDock = false,
                            PinToTop = false
                        },
                        new
                        {
                            UserId = "msaspnet-core-user-hack-system000002",
                            ProgramId = "program0-icon-0828-hack-system000008",
                            Hide = false,
                            PinToDock = true,
                            PinToTop = false
                        },
                        new
                        {
                            UserId = "msaspnet-core-user-hack-system000002",
                            ProgramId = "program0-icon-0828-hack-system000009",
                            Hide = false,
                            PinToDock = true,
                            PinToTop = false
                        },
                        new
                        {
                            UserId = "msaspnet-core-user-hack-system000003",
                            ProgramId = "program0-icon-0828-hack-system000001",
                            Hide = false,
                            PinToDock = true,
                            PinToTop = false
                        },
                        new
                        {
                            UserId = "msaspnet-core-user-hack-system000003",
                            ProgramId = "program0-icon-0828-hack-system000002",
                            Hide = false,
                            PinToDock = true,
                            PinToTop = false
                        },
                        new
                        {
                            UserId = "msaspnet-core-user-hack-system000003",
                            ProgramId = "program0-icon-0828-hack-system000003",
                            Hide = false,
                            PinToDock = true,
                            PinToTop = false
                        },
                        new
                        {
                            UserId = "msaspnet-core-user-hack-system000003",
                            ProgramId = "program0-icon-0828-hack-system000004",
                            Hide = false,
                            PinToDock = true,
                            PinToTop = false
                        },
                        new
                        {
                            UserId = "msaspnet-core-user-hack-system000003",
                            ProgramId = "program0-icon-0828-hack-system000005",
                            Hide = false,
                            PinToDock = true,
                            PinToTop = false
                        },
                        new
                        {
                            UserId = "msaspnet-core-user-hack-system000003",
                            ProgramId = "program0-icon-0828-hack-system000006",
                            Hide = false,
                            PinToDock = true,
                            PinToTop = false
                        },
                        new
                        {
                            UserId = "msaspnet-core-user-hack-system000003",
                            ProgramId = "program0-icon-0828-hack-system000007",
                            Hide = false,
                            PinToDock = false,
                            PinToTop = false
                        },
                        new
                        {
                            UserId = "msaspnet-core-user-hack-system000003",
                            ProgramId = "program0-icon-0828-hack-system000008",
                            Hide = false,
                            PinToDock = true,
                            PinToTop = false
                        },
                        new
                        {
                            UserId = "msaspnet-core-user-hack-system000003",
                            ProgramId = "program0-icon-0828-hack-system000009",
                            Hide = false,
                            PinToDock = true,
                            PinToTop = false
                        });
                });

            modelBuilder.Entity("HackSystem.WebAPI.Model.Mock.MockRouteDetail", b =>
                {
                    b.Property<int>("RouteID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("DelayDuration")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("Enabled")
                        .HasColumnType("INTEGER");

                    b.Property<string>("ForwardAddress")
                        .HasColumnType("TEXT");

                    b.Property<string>("ForwardMethod")
                        .HasColumnType("TEXT");

                    b.Property<int>("ForwardMockType")
                        .HasColumnType("INTEGER");

                    b.Property<string>("ForwardRequestBodyTemplate")
                        .HasColumnType("TEXT");

                    b.Property<string>("MockMethod")
                        .HasColumnType("TEXT")
                        .UseCollation("NOCASE");

                    b.Property<string>("MockSourceHost")
                        .HasColumnType("TEXT")
                        .UseCollation("NOCASE");

                    b.Property<int>("MockType")
                        .HasColumnType("INTEGER");

                    b.Property<string>("MockURI")
                        .HasColumnType("TEXT")
                        .UseCollation("NOCASE");

                    b.Property<string>("ResponseBodyTemplate")
                        .HasColumnType("TEXT");

                    b.Property<string>("RouteName")
                        .HasColumnType("TEXT");

                    b.Property<int>("StatusCode")
                        .HasColumnType("INTEGER");

                    b.HasKey("RouteID");

                    b.HasIndex("Enabled");

                    b.HasIndex("MockURI", "MockMethod", "MockSourceHost")
                        .IsUnique();

                    b.ToTable("MockRouteDetails");
                });

            modelBuilder.Entity("HackSystem.WebAPI.Model.Mock.MockRouteLogDetail", b =>
                {
                    b.Property<int>("RouteLogID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("ConnectionID")
                        .HasColumnType("TEXT");

                    b.Property<string>("Exception")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("FinishDateTime")
                        .HasColumnType("TEXT");

                    b.Property<string>("ForwardAddress")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("ForwardDateTime")
                        .HasColumnType("TEXT");

                    b.Property<string>("ForwardMethod")
                        .HasColumnType("TEXT");

                    b.Property<int>("ForwardMockType")
                        .HasColumnType("INTEGER");

                    b.Property<string>("ForwardRequestBodyTemplate")
                        .HasColumnType("TEXT");

                    b.Property<string>("ForwardResponseBody")
                        .HasColumnType("TEXT");

                    b.Property<int>("ForwardResponseStatusCode")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Method")
                        .HasColumnType("TEXT");

                    b.Property<int>("MockRouteLogStatus")
                        .HasColumnType("INTEGER");

                    b.Property<int>("MockType")
                        .HasColumnType("INTEGER");

                    b.Property<string>("RequestBody")
                        .HasColumnType("TEXT");

                    b.Property<string>("ResponseBody")
                        .HasColumnType("TEXT");

                    b.Property<int>("RouteID")
                        .HasColumnType("INTEGER");

                    b.Property<string>("SourceHost")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("StartDateTime")
                        .HasColumnType("TEXT");

                    b.Property<int>("StatusCode")
                        .HasColumnType("INTEGER");

                    b.Property<string>("URI")
                        .HasColumnType("TEXT");

                    b.HasKey("RouteLogID");

                    b.HasIndex("RouteID");

                    b.HasIndex("URI", "Method", "SourceHost", "MockType");

                    b.ToTable("MockRouteLogDetails");
                });

            modelBuilder.Entity("HackSystem.WebAPI.Model.Option.GenericOption", b =>
                {
                    b.Property<int>("OptionID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Category")
                        .HasColumnType("TEXT")
                        .UseCollation("NOCASE");

                    b.Property<DateTime>("CreateTime")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("ModifyTime")
                        .HasColumnType("TEXT");

                    b.Property<string>("OptionName")
                        .HasColumnType("TEXT")
                        .UseCollation("NOCASE");

                    b.Property<string>("OptionValue")
                        .HasColumnType("TEXT");

                    b.Property<string>("OwnerLevel")
                        .HasColumnType("TEXT")
                        .UseCollation("NOCASE");

                    b.HasKey("OptionID");

                    b.HasIndex("OptionName");

                    b.HasIndex("OwnerLevel", "OptionName");

                    b.HasIndex("OwnerLevel", "Category", "OptionName")
                        .IsUnique();

                    b.ToTable("GenericOptions");
                });

            modelBuilder.Entity("HackSystem.WebAPI.Model.Program.BasicProgram", b =>
                {
                    b.Property<string>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("AssemblyName")
                        .HasColumnType("TEXT");

                    b.Property<bool>("Enabled")
                        .HasColumnType("INTEGER");

                    b.Property<string>("IconUri")
                        .HasColumnType("TEXT");

                    b.Property<bool>("Integral")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IsSingleton")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .HasColumnType("TEXT");

                    b.Property<string>("TypeName")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("Id", "Name");

                    b.ToTable("BasicPrograms");

                    b.HasData(
                        new
                        {
                            Id = "program0-icon-0828-hack-system000001",
                            AssemblyName = "HackSystem.Web.SystemProgram",
                            Enabled = true,
                            IconUri = "/images/ProgramIcons/HomeProgram.png",
                            Integral = true,
                            IsSingleton = true,
                            Name = "Home",
                            TypeName = "HackSystem.Web.SystemProgram.Home.HomeComponent"
                        },
                        new
                        {
                            Id = "program0-icon-0828-hack-system000002",
                            AssemblyName = "HackSystem.Web.SystemProgram",
                            Enabled = true,
                            IconUri = "/images/ProgramIcons/ExplorerProgram.png",
                            Integral = true,
                            IsSingleton = false,
                            Name = "Explorer",
                            TypeName = "HackSystem.Web.SystemProgram.Explorer.ExplorerComponent"
                        },
                        new
                        {
                            Id = "program0-icon-0828-hack-system000003",
                            AssemblyName = "HackSystem.Web.SystemProgram",
                            Enabled = true,
                            IconUri = "/images/ProgramIcons/BorwserProgram.png",
                            Integral = true,
                            IsSingleton = false,
                            Name = "Borwser",
                            TypeName = "HackSystem.Web.SystemProgram.Borwser.BorwserComponent"
                        },
                        new
                        {
                            Id = "program0-icon-0828-hack-system000004",
                            AssemblyName = "HackSystem.Web.SystemProgram",
                            Enabled = true,
                            IconUri = "/images/ProgramIcons/ProfileProgram.png",
                            Integral = true,
                            IsSingleton = true,
                            Name = "Profile",
                            TypeName = "HackSystem.Web.SystemProgram.Profile.ProfileComponent"
                        },
                        new
                        {
                            Id = "program0-icon-0828-hack-system000005",
                            AssemblyName = "HackSystem.Web.SystemProgram",
                            Enabled = true,
                            IconUri = "/images/ProgramIcons/SettingProgram.png",
                            Integral = true,
                            IsSingleton = true,
                            Name = "Setting",
                            TypeName = "HackSystem.Web.SystemProgram.Setting.SettingComponent"
                        },
                        new
                        {
                            Id = "program0-icon-0828-hack-system000006",
                            AssemblyName = "HackSystem.Web.SystemProgram",
                            Enabled = true,
                            IconUri = "/images/ProgramIcons/AppStoreProgram.png",
                            Integral = true,
                            IsSingleton = true,
                            Name = "AppStore",
                            TypeName = "HackSystem.Web.SystemProgram.AppStore.AppStoreComponent"
                        },
                        new
                        {
                            Id = "program0-icon-0828-hack-system000007",
                            AssemblyName = "HackSystem.Web.SystemProgram",
                            Enabled = true,
                            IconUri = "/images/ProgramIcons/WeatherProgram.png",
                            Integral = false,
                            IsSingleton = true,
                            Name = "Weather",
                            TypeName = "HackSystem.Web.SystemProgram.Weather.WeatherComponent"
                        },
                        new
                        {
                            Id = "program0-icon-0828-hack-system000008",
                            AssemblyName = "HackSystem.Web.SystemProgram",
                            Enabled = true,
                            IconUri = "/images/ProgramIcons/TaskServerProgram.png",
                            Integral = true,
                            IsSingleton = true,
                            Name = "TaskServer",
                            TypeName = "HackSystem.Web.SystemProgram.TaskServer.TaskServerComponent"
                        },
                        new
                        {
                            Id = "program0-icon-0828-hack-system000009",
                            AssemblyName = "HackSystem.Web.SystemProgram",
                            Enabled = true,
                            IconUri = "/images/ProgramIcons/MockServerProgram.png",
                            Integral = true,
                            IsSingleton = true,
                            Name = "MockServer",
                            TypeName = "HackSystem.Web.SystemProgram.MockServer.MockServerComponent"
                        });
                });

            modelBuilder.Entity("HackSystem.WebAPI.Model.Task.TaskDetail", b =>
                {
                    b.Property<int>("TaskID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("AssemblyName")
                        .HasColumnType("TEXT");

                    b.Property<TimeSpan>("AutomaticInterval")
                        .HasColumnType("TEXT");

                    b.Property<string>("Category")
                        .HasColumnType("TEXT");

                    b.Property<string>("ClassName")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreateTime")
                        .HasColumnType("TEXT");

                    b.Property<bool>("Enabled")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("ExecuteDateTime")
                        .HasColumnType("TEXT");

                    b.Property<TimeSpan>("FirstInterval")
                        .HasColumnType("TEXT");

                    b.Property<string>("Parameters")
                        .HasColumnType("TEXT");

                    b.Property<string>("ProcedureName")
                        .HasColumnType("TEXT");

                    b.Property<bool>("Reentrant")
                        .HasColumnType("INTEGER");

                    b.Property<int>("TaskFrequency")
                        .HasColumnType("INTEGER");

                    b.Property<string>("TaskName")
                        .HasColumnType("TEXT");

                    b.HasKey("TaskID");

                    b.HasIndex("Enabled");

                    b.HasIndex("TaskName")
                        .IsUnique();

                    b.HasIndex("TaskName", "ExecuteDateTime");

                    b.ToTable("TaskDetails");

                    b.HasData(
                        new
                        {
                            TaskID = 1,
                            AssemblyName = "HackSystem.WebAPI.Tasks",
                            AutomaticInterval = new TimeSpan(0, 0, 0, 0, 0),
                            Category = "HackSystem",
                            ClassName = "HackSystem.WebAPI.Tasks.DatabaseBackup.IDatabaseBackupTask",
                            CreateTime = new DateTime(2021, 7, 24, 14, 3, 30, 0, DateTimeKind.Unspecified),
                            Enabled = true,
                            ExecuteDateTime = new DateTime(2021, 7, 24, 5, 0, 0, 0, DateTimeKind.Unspecified),
                            FirstInterval = new TimeSpan(0, 0, 0, 0, 0),
                            Parameters = "OriginDB=DATA SOURCE=.\\HackSystem.db|BackupDB=DATA SOURCE=.\\HackSystem_backup_{0}.db",
                            ProcedureName = "Execute",
                            Reentrant = false,
                            TaskFrequency = 3,
                            TaskName = "Database Auto Backup"
                        });
                });

            modelBuilder.Entity("HackSystem.WebAPI.Model.Task.TaskLogDetail", b =>
                {
                    b.Property<int>("TaskLogID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Exception")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("FinishDateTime")
                        .HasColumnType("TEXT");

                    b.Property<string>("Parameters")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("StartDateTime")
                        .HasColumnType("TEXT");

                    b.Property<int>("TaskID")
                        .HasColumnType("INTEGER");

                    b.Property<int>("TaskLogStatus")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Trigger")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("TriggerDateTime")
                        .HasColumnType("TEXT");

                    b.HasKey("TaskLogID");

                    b.HasIndex("TaskID");

                    b.HasIndex("TaskID", "TaskLogStatus");

                    b.ToTable("TaskLogDetails");
                });

            modelBuilder.Entity("HackSystem.WebAPI.Model.WebLog.WebAPILog", b =>
                {
                    b.Property<int>("WebAPILogID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<long>("ElapsedTime")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Exception")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("FinishDateTime")
                        .HasColumnType("TEXT");

                    b.Property<string>("IdentityName")
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsAuthenticated")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Method")
                        .HasColumnType("TEXT");

                    b.Property<string>("QueryString")
                        .HasColumnType("TEXT");

                    b.Property<string>("RequestBody")
                        .HasColumnType("TEXT");

                    b.Property<string>("RequestURI")
                        .HasColumnType("TEXT");

                    b.Property<string>("ResponseBody")
                        .HasColumnType("TEXT");

                    b.Property<string>("SourceHost")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("StartDateTime")
                        .HasColumnType("TEXT");

                    b.Property<int>("StatusCode")
                        .HasColumnType("INTEGER");

                    b.Property<string>("TraceIdentifier")
                        .HasColumnType("TEXT");

                    b.Property<string>("UserAgent")
                        .HasColumnType("TEXT");

                    b.HasKey("WebAPILogID");

                    b.HasIndex("RequestURI", "SourceHost", "IdentityName", "StartDateTime");

                    b.ToTable("WebAPILogs");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("ClaimType")
                        .HasColumnType("TEXT");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("TEXT");

                    b.Property<string>("RoleId")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetRoleClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("ClaimType")
                        .HasColumnType("TEXT");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("TEXT");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserClaims", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            ClaimType = "Professional",
                            ClaimValue = "true",
                            UserId = "msaspnet-core-user-hack-system000001"
                        });
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.Property<string>("LoginProvider")
                        .HasColumnType("TEXT");

                    b.Property<string>("ProviderKey")
                        .HasColumnType("TEXT");

                    b.Property<string>("ProviderDisplayName")
                        .HasColumnType("TEXT");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("LoginProvider", "ProviderKey");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserLogins", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("TEXT");

                    b.Property<string>("RoleId")
                        .HasColumnType("TEXT");

                    b.HasKey("UserId", "RoleId");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetUserRoles", (string)null);

                    b.HasData(
                        new
                        {
                            UserId = "msaspnet-core-user-hack-system000001",
                            RoleId = "msaspnet-core-role-hack-system000001"
                        },
                        new
                        {
                            UserId = "msaspnet-core-user-hack-system000001",
                            RoleId = "msaspnet-core-role-hack-system000002"
                        },
                        new
                        {
                            UserId = "msaspnet-core-user-hack-system000002",
                            RoleId = "msaspnet-core-role-hack-system000002"
                        },
                        new
                        {
                            UserId = "msaspnet-core-user-hack-system000003",
                            RoleId = "msaspnet-core-role-hack-system000001"
                        });
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("TEXT");

                    b.Property<string>("LoginProvider")
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .HasColumnType("TEXT");

                    b.Property<string>("Value")
                        .HasColumnType("TEXT");

                    b.HasKey("UserId", "LoginProvider", "Name");

                    b.ToTable("AspNetUserTokens", (string)null);
                });

            modelBuilder.Entity("HackSystem.WebAPI.Model.Map.UserMap.UserBasicProgramMap", b =>
                {
                    b.HasOne("HackSystem.WebAPI.Model.Program.BasicProgram", "BasicProgram")
                        .WithMany("UserProgramMaps")
                        .HasForeignKey("ProgramId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("HackSystem.WebAPI.Model.Identity.HackSystemUser", "User")
                        .WithMany("UserProgramMaps")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("BasicProgram");

                    b.Navigation("User");
                });

            modelBuilder.Entity("HackSystem.WebAPI.Model.Mock.MockRouteLogDetail", b =>
                {
                    b.HasOne("HackSystem.WebAPI.Model.Mock.MockRouteDetail", null)
                        .WithMany()
                        .HasForeignKey("RouteID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("HackSystem.WebAPI.Model.Task.TaskLogDetail", b =>
                {
                    b.HasOne("HackSystem.WebAPI.Model.Task.TaskDetail", null)
                        .WithMany()
                        .HasForeignKey("TaskID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.HasOne("HackSystem.WebAPI.Model.Identity.HackSystemRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.HasOne("HackSystem.WebAPI.Model.Identity.HackSystemUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.HasOne("HackSystem.WebAPI.Model.Identity.HackSystemUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.HasOne("HackSystem.WebAPI.Model.Identity.HackSystemRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("HackSystem.WebAPI.Model.Identity.HackSystemUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.HasOne("HackSystem.WebAPI.Model.Identity.HackSystemUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("HackSystem.WebAPI.Model.Identity.HackSystemUser", b =>
                {
                    b.Navigation("UserProgramMaps");
                });

            modelBuilder.Entity("HackSystem.WebAPI.Model.Program.BasicProgram", b =>
                {
                    b.Navigation("UserProgramMaps");
                });
#pragma warning restore 612, 618
        }
    }
